# Generated by Django 3.0.6 on 2020-05-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default/profile.jpg', upload_to='users/profiles'),
        ),
    ]
