            name='profile_image',
from django.db import migrations, models
class Migration(migrations.Migration):
        ),
# Generated by Django 3.0.6 on 2020-05-31 00:09
    dependencies = [
            field=models.ImageField(blank=True, default='default/profile.jpg', upload_to='users/profiles'),





    ]
    ]
        migrations.AddField(
        ('users', '0001_initial'),
    operations = [
            model_name='customuser',
