# Generated by Django 3.0.6 on 2020-06-14 15:30

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200614_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagen_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='defaults/profile.jpg', force_format=None, keep_meta=True, null=True, quality=100, size=[500, 500], upload_to='users/profile'),
        ),
    ]
