# Generated by Django 3.0.6 on 2020-05-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tribute',
            name='anecdote',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tribute',
            name='quote',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tribute',
            name='writting',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
