# Generated by Django 3.0.6 on 2020-05-30 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0017_auto_20200530_2141'),
        ('tributes', '0002_auto_20200530_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribute',
            name='memorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tributes', to='memorials.Memorial'),
            preserve_default=False,
        ),
    ]
