# Generated by Django 3.0.6 on 2020-05-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0003_tribute_memorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribute',
            old_name='image',
            new_name='cover_image',
        ),
    ]
