# Generated by Django 3.0.6 on 2020-06-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0004_auto_20200530_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribute',
            name='quote_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
