# Generated by Django 3.0.6 on 2020-06-08 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0005_tribute_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
