# Generated by Django 3.0.6 on 2020-06-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributes', '0006_comment_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
