# Generated by Django 3.0.6 on 2020-05-15 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memorials', '0014_delete_eulogy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eulogy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(blank=True, max_length=200, null=True)),
                ('anecdote', models.TextField(blank=True, max_length=300, null=True)),
                ('writting', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, db_index=True, null=True, upload_to='')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eulogy', to='memorials.Memorial')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
