# Generated by Django 3.0.6 on 2020-05-17 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('second_first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('second_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('biography', models.TextField(max_length=10000)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_passing', models.DateField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='users.CustomUser')),
            ],
        ),
    ]
