# Generated by Django 3.0.6 on 2020-05-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('descrition', models.TextField(max_length=300)),
                ('first_names', models.CharField(blank=True, max_length=200, null=True)),
                ('last_names', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
