# Generated by Django 3.0.6 on 2020-05-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorial',
            old_name='descrition',
            new_name='biography',
        ),
    ]
