# Generated by Django 3.0.6 on 2020-05-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0002_auto_20200517_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorial',
            old_name='creator',
            new_name='author',
        ),
    ]
