# Generated by Django 3.0.6 on 2020-05-14 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0003_auto_20200514_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eulogy',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorials.Memorial'),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
