# Generated by Django 3.0.6 on 2020-05-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('memorials', '0003_auto_20200517_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser'),
        ),
    ]
