# Generated by Django 3.0.6 on 2020-05-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0004_auto_20200517_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='cover_image',
            field=models.ImageField(blank=True, default='media/defaults/default.jpg', null=True, upload_to='covers/'),
        ),
    ]
