# Generated by Django 3.0.6 on 2020-05-14 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0005_auto_20200514_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eulogy',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eulogy', to='memorials.Memorial'),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
