# Generated by Django 3.0.6 on 2020-05-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0008_auto_20200518_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='cover_image',
            field=models.ImageField(blank=True, default='defaults/cover.jpg', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
