# Generated by Django 3.0.6 on 2020-05-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0010_auto_20200518_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorial',
            old_name='author',
            new_name='created_by',
        ),
    ]
