# Generated by Django 3.0.6 on 2020-05-21 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0011_auto_20200519_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorial',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='biography',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='created_by',
            new_name='creado_por',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='date_of_passing',
            new_name='fecha_de_muerte',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='date_of_birth',
            new_name='fecha_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='cover_image',
            new_name='image_de_fondo',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='profile_image',
            new_name='imagen_de_perfil',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='first_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='second_last_name',
            new_name='segundo_apellido',
        ),
        migrations.RenameField(
            model_name='memorial',
            old_name='second_first_name',
            new_name='segundo_nombre',
        ),
    ]
