# Generated by Django 3.0.6 on 2020-05-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0013_auto_20200514_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eulogy',
        ),
    ]
