# Generated by Django 3.0.6 on 2020-05-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0014_delete_eulogy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='cover_image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='profile_image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='profiles/'),
        ),
    ]
