# Generated by Django 3.0.6 on 2020-05-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0015_auto_20200516_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='cover_image',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='profile_image',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
