# Generated by Django 3.0.6 on 2020-05-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0016_memorial_epitafo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='epitafo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
