# Generated by Django 3.0.6 on 2020-06-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0017_auto_20200530_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='epitafo',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
