# Generated by Django 3.0.6 on 2020-06-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0019_auto_20200608_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='desciption',
            new_name='description',
        ),
    ]
