# Generated by Django 3.0.6 on 2020-06-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0020_auto_20200609_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memorials.Memorial'),
        ),
    ]
