# Generated by Django 3.0.6 on 2020-06-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0021_auto_20200609_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
