# Generated by Django 3.0.6 on 2020-06-10 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memorials', '0022_auto_20200609_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_date', models.DateTimeField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='memorials.Memorial')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
