# Generated by Django 3.0.6 on 2020-06-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0023_lifeevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='picture',
            new_name='file',
        ),
    ]
