# Generated by Django 3.0.6 on 2020-06-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0024_auto_20200610_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorial',
            options={'permissions': (('can add tribute', 'can_add_tribute'), ('can_add_content', 'can add content'), ('can_view_content', 'can view content'))},
        ),
    ]
