# Generated by Django 3.0.6 on 2020-06-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0025_auto_20200613_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial', to='memorials.Memorial')),
            ],
        ),
    ]
