# Generated by Django 3.0.6 on 2020-06-14 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memorials', '0026_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='relation_name',
            field=models.CharField(choices=[('Parent', 'Padre'), ('Parent', 'Madre'), ('Grandparent', 'Abuelo'), ('Grandparent', 'Abuela'), ('Sibling', 'Hermano'), ('Sibling', 'Hermana'), ('Cousin', 'Primo'), ('Cousin', 'Prima'), ('Significant_other', 'Novio'), ('Significant_other', 'Novia'), ('Spouse', 'Esposo'), ('Spouse', 'Esposa'), ('Friend', 'Amigo'), ('Friend', 'Amigo Cercano')], default='Friend', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relation',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_memorial', to='memorials.Memorial'),
        ),
    ]
