# Generated by Django 3.0.6 on 2020-06-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0029_auto_20200614_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relation_name',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Primo', 'Primo'), ('Prima', 'Prima'), ('Novio', 'Novio'), ('Novia', 'Novia'), ('Esposo', 'Esposo'), ('Esposa', 'Esposa'), ('Amigo', 'Amigo'), ('Amigo Cercano', 'Amigo Cercano')], max_length=100),
        ),
    ]
